FROM ctfd/ctfd:3.8.7

USER root
COPY requirements.txt /tmp/challenge-containers-requirements.txt
RUN /opt/venv/bin/python -m pip install --no-cache-dir -r /tmp/challenge-containers-requirements.txt \
    && rm /tmp/challenge-containers-requirements.txt
RUN mkdir -p /opt/challenge-containers-source
COPY --chown=1001:1001 __init__.py /opt/challenge-containers-source/
COPY --chown=1001:1001 src /opt/challenge-containers-source/src
COPY --chown=1001:1001 tests /opt/challenge-containers-source/tests
USER 1001
